### ISSUE TITLE
Plugin fails when "FlutterGooglePlacePicker.launchPlacePicker" is called

### ISSUE THREAD

**Issue by MehndirattaPiyush** [a2en/flutter_google_place_picker#1]
Error Stack
type 'Future<dynamic>' is not a subtype of type 'Future<Map<dynamic, dynamic>>'

E/flutter (31523): #0      FlutterGooglePlacePicker.launchPlacePicker (package:flutter_google_place_picker/flutter_google_place_picker.dart:10:16)
E/flutter (31523): #1      _MyAppState.pickPlace (file:///Users/piyushmehndiratta/Desktop/flutterer/ultrahack/lib/main.dart:32:41)
E/flutter (31523): <asynchronous suspension>
E/flutter (31523): #2      _MyAppState.build.<anonymous closure> (file:///Users/piyushmehndiratta/Desktop/flutterer/ultrahack/lib/main.dart:68:23)
E/flutter (31523): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
E/flutter (31523): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
E/flutter (31523): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (31523): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (31523): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (31523): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (31523): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (31523): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (31523): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (31523): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (31523): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (31523): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (31523): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (31523): #16     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (31523): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

The place picker activity is launched but nothing is returned

**Comment by skillFocus16** [comment]
Experiencing the same thing. Please help!! 

type 'Future<dynamic>' is not a subtype of type 'Future<Map<dynamic, dynamic>>'
E/flutter (26611): #0      FlutterGooglePlacePicker.launchPlacePicker (package:flutter_google_place_picker/flutter_google_place_picker.dart:10:16)
E/flutter (26611): #1      _MapViewPageState.PickPlace (package:thirsty_app/ui/map_view_page.dart:224:46)
E/flutter (26611): <asynchronous suspension>
E/flutter (26611): #2      _MapViewPageState._buildTextBody.<anonymous closure> (package:thirsty_app/ui/map_view_page.dart:485:17)
E/flutter (26611): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter (26611): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter (26611): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (26611): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (26611): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter (26611): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (26611): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (26611): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (26611): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (26611): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (26611): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (26611): #14     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (26611): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

**Comment by miguelpruivo** [comment]
Fixed with my PR [#4](https://github.com/a2en/flutter_google_place_picker/pull/4).
